apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "build-portal.fullname" . }}-env
  labels:
    {{- include "build-portal.labels" . | nindent 4 }}
data:
{{- $root := . -}}
{{- range $k, $v := .Values.config }}
  {{ $k }}: {{ tpl (toString $v) $root | quote }}
{{- end }}
