{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "build-portal.fullname" . }}
  labels:
    {{- include "build-portal.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.gateway.host | quote }}
    {{- with .Values.gateway.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.parentRef.name }}
      namespace: {{ .Values.gateway.parentRef.namespace }}
      {{- with .Values.gateway.parentRef.sectionName }}
      sectionName: {{ . }}
      {{- end }}
  hostnames:
    - {{ .Values.gateway.host | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - kind: Service
          name: {{ default (include "build-portal.fullname" .) .Values.service.name }}
          port: {{ .Values.service.port }}
{{- end }}
