{{- if .Values.secrets }}
{{- $root := . -}}
{{- $cfg := .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "build-portal.fullname" . }}
  labels:
    {{- include "build-portal.labels" $root | nindent 4 }}
  {{- with (get $cfg "annotations") }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ default "Opaque" (get $cfg "type") }}
stringData:
{{- range $k, $v := $cfg }}
{{- if and (ne $k "type") (ne $k "name") (ne $k "labels") (ne $k "annotations") }}
  {{ $k }}: {{ tpl (toString $v) $root | quote }}
{{- end }}
{{- end }}
{{- end }}
