apiVersion: v1
kind: Service
metadata:
  name: {{ include "build-portal.fullname" . }}
  labels:
    {{- include "build-portal.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAnnotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "build-portal.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}          # 80
      targetPort: {{ .Values.containerPort }}   # 8080
